### ISSUE TITLE
懇親会の会場を決める

### ISSUE THREAD

**Issue by kurotaky** [k-ruby/kagoshima-rubykaigi02#15]
18:00に完全撤収したら、その後懇親会へ移動したい。
18:30~20:30 くらいで開催予定。(18:00開始位でも良いかも)

30~40名くらい入れるところがあれば。さくらじまハウス 2022で行ったところとかも良いかも。

**Comment by kurotaky** [comment]
https://k-wakana.com/about/ よさそう

**Comment by yoshikouki** [comment]
@HouraiSyuto がお店事情に詳しいので、是非お願いしたく！

**Comment by HouraiSyuto** [comment]
- https://daigoro-kagoshima.jp/
- https://www.instagram.com/kisetuya_kyu/
- https://www.maita-kagoshima.com/

この店なら 30~40名くらい入れそう。
マーク名山近くは小さい居酒屋しかなさそうなので、場所は天文館でピックアップしました。

**Comment by HouraiSyuto** [comment]
大五郎予約しました
https://daigoro-kagoshima.jp/

日にち：3/4
時間：18:30
人数：34人
コース：6000円
予約者：ホウライ

**Comment by kurotaky** [comment]
https://k-ruby.connpass.com/event/275650/ で参加者募集中 📝

**Comment by yoshikouki** [comment]
予約一杯になりました！最高！

@HouraiSyuto 人数の連絡はやってもらいました？
完了していましたら Close しましょう〜

**Comment by HouraiSyuto** [comment]
34人で人数の連絡しました！こちらクローズしちゃいます！
