### ISSUE TITLE
鹿児島Ruby会議02のデザインまわり

### ISSUE THREAD

**Issue by kaori221b** [k-ruby/kagoshima-rubykaigi02#3]
### URL
http://test.thread.jp/ruby/ 
※ダミー

公開URL
https://k-ruby.com/kagoshima-rubykaigi02/

### タスク

- [x] [「 鹿児島Ruby会議02について」テキスト原稿](https://github.com/k-ruby/kagoshima-rubykaigi02/issues/6)
- [ ] 招待公演
- [ ] [タイムスケジュール](https://github.com/k-ruby/kagoshima-rubykaigi02/issues/9)
- [x] [行動規範](https://github.com/k-ruby/kagoshima-rubykaigi02/issues/1)
- [x] フォントファミリー設定
- [x] ファビコン
- [x] OGP
- [x] GTM設定
　　GAでPC/SPユーザーどちらが多いのか（スマホファーストのレイアウトでいいのか）
　　流入経路の特定・コンテンツの閲覧・スクロール量など
　　次回開催時に活かせるようにする

**Comment by yoshikouki** [comment]
PC|スマホ
---|---
![screencapture-127-0-0-1-5500-index-html-2023-02-04-13_00_26](https://user-images.githubusercontent.com/53972292/216746804-e25a15ab-5e94-4268-93ca-ecfce62c0826.jpg)|![screencapture-127-0-0-1-5500-index-html-2023-02-04-12_59_46](https://user-images.githubusercontent.com/53972292/216746787-9bf2750f-4c89-4f44-9b27-6e3b17fd6dc1.jpg)

**Comment by yoshikouki** [comment]
> - [ ] ファビコン

このコミット https://github.com/k-ruby/k-ruby.github.io/commit/1d7db3f37243eb64a9d5a165d8c27f809122f484 で公開テストをやったところ、期待通りファビコンも表示された

![PixelSnap 2023-02-04 at 15 16 32@2x](https://user-images.githubusercontent.com/53972292/216752326-584ddbe1-3625-4ad3-a849-7f1c11bf74a1.png)

**Comment by yoshikouki** [comment]
公開した

https://k-ruby.com/kagoshima-rubykaigi02/

https://github.com/k-ruby/k-ruby.github.io で当リポジトリを Git Submodule として読み込んで公開している

残りのタスクは招待講演とタイムスケジュールで、決定次第公開する

> ### タスク
> 
> - [ ] 招待公演
> - [ ] [タイムスケジュール](https://github.com/k-ruby/kagoshima-rubykaigi02/issues/9)

**Comment by kurotaky** [comment]
- 12:00~18:00 に変更
  - 片付けなども参加者含めてみんなでやるので、ほぼ完全撤収する時間に合わせる
- 招待講演は無しで、代わりに `スピーカー` or `Speakers` にして、登壇者のTwitterアイコンと講演タイトルを載せる

イメージこんな感じです !
<img width="1292" alt="スクリーンショット 2023-02-11 10 02 16" src="https://user-images.githubusercontent.com/866589/218228822-295abd18-c5f6-4313-8596-2a00151bd620.png">
https://rubykaigi.org/2022/speakers/

ここまでやったら一旦Twitterで宣伝したいです 🙏

**Comment by yoshikouki** [comment]
スマホ画面のスクショが途切れ途切れになっていますが、キャプチャ拡張機能の不具合によるものであり、しっかり表示されています (なので参考程度にしてください)

PC|スマホ
---|---
![screencapture-127-0-0-1-5500-index-html-2023-02-11-23_46_33](https://user-images.githubusercontent.com/53972292/218264250-16136f58-d6a8-4de6-bc9a-2cfac7adf559.jpg)|![screencapture-127-0-0-1-5500-index-html-2023-02-11-23_47_18](https://user-images.githubusercontent.com/53972292/218264282-33552f7b-0b65-442f-9392-8208ed6be7d2.jpg)

**Comment by yoshikouki** [comment]
画像を差し替えた現時点のバージョン

![screencapture-127-0-0-1-5500-index-html-2023-02-13-11_15_22](https://user-images.githubusercontent.com/53972292/218355591-30491e64-f124-41bf-ad30-e41f3ecd190e.jpg)
