### ISSUE TITLE
スポンサーの募集

### ISSUE THREAD

**Issue by kurotaky** [k-ruby/kagoshima-rubykaigi02#8]
@llnozaki さんと進めています。

前回協賛頂いた6社はスポンサーになって頂けそうです!
https://k-ruby.com/kagoshima-rubykaigi01/

スポンサー費用の振込みについて https://github.com/ruby-no-kai/official/issues/451#issuecomment-1403949366 で相談はしています。

👇 ざっくりとしたスケジュール感です。
```
- 日本Rubyの会からK-Rubyメンバーの口座に振り込んでいただく (2月下旬)
- スポンサー企業から日本のRubyの会に振り込みをしていただく (2月末または3月末期限)
```

**Comment by kurotaky** [comment]
01の時と同じようにスポンサー費用のやりとりをRubyの会 高橋さまと進めています。
- Rubyの会からK-Ruby黒瀧の口座にスポンサー費用をまとめて振り込んで頂く(3/3までに振り込まれる)
- 3月末期限でRubyの会から請求書を発行してもらい、スポンサー企業の担当者に連絡しお支払いの手続きを進めてもらう

```
Rubyの会の高橋征義です。下記メールありがとうございます。もろもろ了解です。

* 振込の件は今月中で問題ないです。
* 請求の件ですが、スポンサーさんに下記について確認してください（確認された内容はメールにあったgoogle
spreadsheet等に書いておいていただければ）。
  * 請求書はメールで良いか、郵送がよいか
    * メールの場合、送付先メールアドレス
    * 郵送の場合、請求書送付先情報（住所、担当者名（＋部署名））

あと、一応請求作業についてはissueにしておくつもりです。合わせてご確認ください。
どうぞよろしくお願いいたします。
```

現在、各スポンサー企業に メール or 郵送 を確認中

**Comment by kurotaky** [comment]
確認が完了した。3月末までに各社で振り込みをしてもらう。

**Comment by kurotaky** [comment]
## スポンサーLTに関して
(仮)
- 13:10〜13:20 リリー
- 14:20〜14:30 ユニマル 
- 15:30〜15:40 現場サポート、ペパボ

📝 
シナプスとWIZはLTなし

**Comment by yoshikouki** [comment]
コーヒーブースのあたりにスポンサー企業の関連アメニティを置くスペースを用意しましょうか
テーブル数脚設置して、その上に置いてもらう形で

@kurotaky 
スポンサーへの連絡をお願いしてもよろしいでしょうか？
移動とかで大変ならやります！

**Comment by kurotaky** [comment]
@yoshikouki 
連絡しました!

**Comment by yoshikouki** [comment]
ありがとうございます！！！
