### ISSUE TITLE
タイムテーブルを決める (開始時間と終了時間)

### ISSUE THREAD

**Issue by kurotaky** [k-ruby/kagoshima-rubykaigi02#9]
基本は前回の01と同じようなタイムラインを想定している。
県外だと東京と福岡からの参加者が多そう。空港へのバスの時刻は考慮して決めておく。

**Comment by kurotaky** [comment]
## タイムスケジュールを考えてみました
1. 13:20〜13:40   yoshikouki  ｢鹿児島からRubyではじめる新規サービス開発｣
2. 13:40〜14:00   杉山恵理子 ｢Ruby に背中を押してもらったコミュニティ参加からオーガナイザーまでの道のり｣
3. 14:30〜14:50  うなすけ  ｢QUICをRubyの世界に持ってくる活動をしています｣
4. 14:50〜15:10  トミー  ｢「初めてRailsアプリをリリースしました！」のその後｣
5. 15:40〜16:00  岡嵜 雄平 ｢mrubyでマイコンの世界に足を踏み入れる｣
6. 16:00〜16:20  大倉雅史 ｢Rubyではじめる自動テスト｣
7. 16:40〜17:00  塩井美咲  ｢たのしいRubyの構文解析ツアー｣
8. 17:00〜17:20  松田 明  ｢Rails 7.1をn倍速くした話｣

https://k-ruby.com/kagoshima-rubykaigi02/#contents02

### 📝 
- 杉山さんが早めに時間帯を希望されていること
- 最初にアイスブレイク込みで会場を盛り上げてくれそうなyoshikoさん
- RailsとRubyのコミッターの松田さんの講演

という感じでタイムスケジュール組んでみました！

**Comment by yoshikouki** [comment]
良さそう！です！
切り込み隊長やりますし、最後が松田さんも楽しみ〜〜〜となりますね

**Comment by yoshikouki** [comment]
公開しました🙆‍♂️

https://k-ruby.com/kagoshima-rubykaigi02/#schedule
